#!/bin/bash

MAKEFILE='Makefile'
AUTOGENERATED_STRING='# AUTOGENERATED BY `g++ -MM`, DO NOT EDIT!'

makefile_content=$(sed "/${AUTOGENERATED_STRING}/Q" "${MAKEFILE}")
echo "${makefile_content}" > "${MAKEFILE}"
echo "" >> "${MAKEFILE}"
echo "${AUTOGENERATED_STRING}" >> "${MAKEFILE}"
g++ -MM *.cpp >> "${MAKEFILE}"
